services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Azarniewicz\SyliusInPostPlugin\:
        resource: '../*'
        exclude: '../{Entity,Model,DependencyInjection}'

    # Factory
    azarniewicz.sylius_inpost_plugin.factory.inpost_point:
        class: Azarniewicz\SyliusInPostPlugin\Factory\InPostPointFactory
        public: true

    Azarniewicz\SyliusInPostPlugin\Factory\InPostPointFactory: '@azarniewicz.sylius_inpost_plugin.factory.inpost_point'

    # Validator
    Azarniewicz\SyliusInPostPlugin\Validator\HasPhoneNumberInPostOrderValidator:
        tags:
            - { name: validator.constraint_validator, alias: azarniewicz_has_phone_number_in_post_order }

    Azarniewicz\SyliusInPostPlugin\Checker\ShippingMethodChecker:
        arguments:
            $shippingMethodCode: '%azarniewicz_sylius_inpost.shipping_method_code%'

    Azarniewicz\SyliusInPostPlugin\Client\InPostApiClient:
        arguments:
            $apiBaseUrl: '%azarniewicz_sylius_inpost.api_base_url%'

    # Controller
    Azarniewicz\SyliusInPostPlugin\Controller\AddPointToOrderAction:
        arguments:
            $inPostPointFactory: '@azarniewicz.sylius_inpost_plugin.factory.inpost_point'
        tags: ['controller.service_arguments']
